
# Generated by Django 4.2.4 on 2023-08-29 20:11


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('prepared_counter', models.BigIntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, null=True)),
                ('recipe_image', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
