# Generated by Django 4.2.4 on 2023-09-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='extendedIngredients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
