# Generated by Django 4.2.4 on 2023-09-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantryitem_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pantryitem',
            old_name='item_name',
            new_name='label',
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='image',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='item_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
